export const MUTATION_KEYS = {
  CREATE_USER: "CREATE_USER",
  CREATE_PERSON: "CREATE_PERSON",
  CREATE_SUPPORTER: "CREATE_SUPPORTER",
  CREATE_DEMAND: "CREATE_DEMAND",
  ANSWER_DEMAND: "ANSWER_DEMAND",
  CREATE_ITEM: "CREATE_ITEM",
};
